### PR TITLE
release 1.4.1

### PR DESCRIPTION
**Pull request by sni**
Signed-off-by: Sven Nierlein <sven@nierlein.de>

### CODE REVIEW

**Review by jacobbaungard — COMMENTED** [review]
I think we've usually added a post also.

Makes it a bit easier to get the the "what's new" page as you would otherwise need to navigate to documentation->user guide->what's new in this version.

Perhaps there should be a easier way to navigate there..

**Comment by sni** [comment]
ay, you're right... will do that :) This is the last PR in the row that needs to be merged anyway.

**Comment by sni** [comment]
added a release post, not much, but there is not much to see anyway :)

**Review by jacobbaungard — APPROVED** [review]
Great, thanks!

**Pull request merged**
