### PR TITLE
Update plugin doc

### PR DESCRIPTION
**Pull request by kjetilho**
hopefully make it easier for the next person to understand how to add perfdata to their plugin by pointing at current URLs and including the main piece of information.

### CODE REVIEW

**Comment by kjetilho** [comment]
Unrelated comment to this documentation: I think the choice of blue to highlight parts of the output is unfortunate since it makes it harder to distinguish what are hyperlinks and what are perfdata components.  I would suggest changing it to "green" and "#00A500" - this looks good on my screen.  But since this is such a personal preference, I won't add a PR for it unless you agree and ask me to :)

**Comment by jacobbaungard** [comment]
I think this is good in general, thanks for sending it in.

However I think most people that uses Naemon these days uses: https://www.monitoring-plugins.org rather than the Nagios (inc) plugins. Could I suggest we find the appropriate links on the monitoring-plugins site and link to these instead?

Alternatively we could link both I guess.

**Comment by sni** [comment]
guess you are looking for this link: https://www.monitoring-plugins.org/doc/guidelines.html#AEN201

**Review by sni — APPROVED** [review]

**Comment by sni** [comment]
thanks

**Pull request merged**
